//! Cross-validation integration tests comparing Rust text module output
//! against expected values from the Python implementations.
//!
//! These tests hardcode expected outputs generated by running the Python
//! functions, ensuring the two implementations remain in sync.

use std::collections::HashSet;

use wxyc_etl::text::batch::batch_normalize;
use wxyc_etl::text::compilation::is_compilation_artist;
use wxyc_etl::text::normalize::{normalize_artist_name, normalize_title, strip_diacritics};
use wxyc_etl::text::split::{split_artist_name, split_artist_name_contextual};

/// Edge cases for normalize_artist_name, verified against Python
/// `filter_csv.py:normalize_artist()`.
#[test]
fn test_normalize_python_parity() {
    // (input, expected_output) from running Python normalize_artist()
    let cases = [
        // Basic Latin diacritics
        ("Björk", "bjork"),
        ("Sigur Rós", "sigur ros"),
        ("Motörhead", "motorhead"),
        ("Hüsker Dü", "husker du"),
        ("Café Tacvba", "cafe tacvba"),
        ("Zoé", "zoe"),
        // Case and whitespace
        ("  RADIOHEAD  ", "radiohead"),
        ("", ""),
        // Multiple diacritics in one name
        ("José González", "jose gonzalez"),
        // Combining tilde (ñ decomposes to n + combining tilde)
        ("Señor Coconut", "senor coconut"),
        // Polish ł (NFKD doesn't decompose ł — it stays as-is)
        ("Łona", "łona"),
        // Japanese (no decomposition expected)
        ("坂本龍一", "坂本龍一"),
    ];

    for (input, expected) in &cases {
        assert_eq!(
            normalize_artist_name(input),
            *expected,
            "normalize_artist_name({:?}) failed",
            input
        );
    }
}

/// Verify strip_diacritics preserves case and whitespace.
#[test]
fn test_strip_diacritics_python_parity() {
    let cases = [
        ("Björk", "Bjork"),
        ("  Café  ", "  Cafe  "),
        ("SIGUR RÓS", "SIGUR ROS"),
        ("normal text", "normal text"),
    ];

    for (input, expected) in &cases {
        assert_eq!(
            strip_diacritics(input),
            *expected,
            "strip_diacritics({:?}) failed",
            input
        );
    }
}

/// Verify normalize_title matches normalize_artist_name.
#[test]
fn test_normalize_title_parity() {
    let inputs = ["OK Computer", "Café Tacvba", "  Sugar Hill  "];
    for input in &inputs {
        assert_eq!(
            normalize_title(input),
            normalize_artist_name(input),
            "normalize_title and normalize_artist_name diverged for {:?}",
            input
        );
    }
}

/// Verify is_compilation_artist against Python matching.py.
#[test]
fn test_compilation_python_parity() {
    let cases = [
        ("Various Artists", true),
        ("various", true),
        ("VARIOUS", true),
        ("Soundtrack", true),
        ("Original Motion Picture Soundtrack", true),
        ("V/A", true),
        ("v.a.", true),
        ("Compilation Hits", true),
        ("Stereolab", false),
        ("Juana Molina", false),
        ("Cat Power", false),
        ("", false),
        ("Jessica Pratt", false),
        ("Chuquimamani-Condori", false),
    ];

    for (input, expected) in &cases {
        assert_eq!(
            is_compilation_artist(input),
            *expected,
            "is_compilation_artist({:?}) failed",
            input
        );
    }
}

/// Verify split_artist_name against Python artist_splitting.py.
#[test]
fn test_split_python_parity() {
    let cases: Vec<(&str, Option<Vec<&str>>)> = vec![
        ("Mike Vainio, Ryoji, Alva Noto", Some(vec!["Mike Vainio", "Ryoji", "Alva Noto"])),
        ("Mika Vainio + Ryoji Ikeda + Alva Noto", Some(vec!["Mika Vainio", "Ryoji Ikeda", "Alva Noto"])),
        ("J Dilla / Jay Dee", Some(vec!["J Dilla", "Jay Dee"])),
        ("Emerson, Lake, and Palmer", Some(vec!["Emerson", "Lake", "Palmer"])),
        ("10,000 Maniacs", None),
        ("Autechre", None),
        ("Duke Ellington & John Coltrane", None),
        ("Andy Human and the Reptoids", None),
        ("", None),
    ];

    for (input, expected) in &cases {
        let result = split_artist_name(input);
        let expected_owned: Option<Vec<String>> =
            expected.as_ref().map(|v| v.iter().map(|s| s.to_string()).collect());
        assert_eq!(
            result, expected_owned,
            "split_artist_name({:?}) failed",
            input
        );
    }
}

/// Verify split_artist_name_contextual against Python.
#[test]
fn test_split_contextual_python_parity() {
    let known: HashSet<String> = ["duke ellington", "john coltrane", "young", "bjork", "god"]
        .iter()
        .map(|s| s.to_string())
        .collect();

    let cases: Vec<(&str, Option<Vec<&str>>)> = vec![
        ("Duke Ellington & John Coltrane", Some(vec!["Duke Ellington", "John Coltrane"])),
        ("Simon & Garfunkel", None),
        ("J Dilla / Jay Dee", Some(vec!["J Dilla", "Jay Dee"])),
        ("Crosby, Stills, Nash & Young", Some(vec!["Crosby", "Stills", "Nash", "Young"])),
        ("Björk & Thom Yorke", Some(vec!["Björk", "Thom Yorke"])),
        ("13 & God", Some(vec!["13", "God"])),
    ];

    for (input, expected) in &cases {
        let result = split_artist_name_contextual(input, &known);
        let expected_owned: Option<Vec<String>> =
            expected.as_ref().map(|v| v.iter().map(|s| s.to_string()).collect());
        assert_eq!(
            result, expected_owned,
            "split_artist_name_contextual({:?}) failed",
            input
        );
    }
}

/// Verify batch_normalize produces same results as individual calls.
#[test]
fn test_batch_normalize_parity() {
    let names: Vec<String> = vec![
        "Björk".into(),
        "Sigur Rós".into(),
        "  Radiohead  ".into(),
        "Café Tacvba".into(),
    ];

    let batch_result = batch_normalize(&names);
    let individual_results: Vec<String> = names.iter().map(|n| normalize_artist_name(n)).collect();

    assert_eq!(batch_result, individual_results);
}
